/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    artists: Artist;
    labels: Label;
    reviews: Review;
    songs: Song;
    gigs: Gig;
    'deep-dives': DeepDive;
    playlists: Playlist;
    notes: Note;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    artists: ArtistsSelect<false> | ArtistsSelect<true>;
    labels: LabelsSelect<false> | LabelsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    songs: SongsSelect<false> | SongsSelect<true>;
    gigs: GigsSelect<false> | GigsSelect<true>;
    'deep-dives': DeepDivesSelect<false> | DeepDivesSelect<true>;
    playlists: PlaylistsSelect<false> | PlaylistsSelect<true>;
    notes: NotesSelect<false> | NotesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists".
 */
export interface Artist {
  id: number;
  name: string;
  slug: string;
  bio?: string | null;
  image?: (number | null) | Media;
  /**
   * Where the artist is from (e.g. "Newcastle, England")
   */
  origin?: string | null;
  /**
   * Year formed or born (e.g. "2017" or "1976")
   */
  founded?: string | null;
  /**
   * Primary genre (e.g. "Indie Rock", "Post-Punk")
   */
  genre?: string | null;
  /**
   * Current or primary label
   */
  label?: (number | null) | Label;
  /**
   * Spotify artist link
   */
  spotifyUrl?: string | null;
  /**
   * Official website
   */
  websiteUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels".
 */
export interface Label {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  title: string;
  /**
   * Optional clickbait/SEO headline. Shows on cards, slider, and social shares. Falls back to "Artist — Title" if empty.
   */
  headline?: string | null;
  slug: string;
  reviewType?: ('album' | 'gig' | 'artist' | 'single' | 'ep' | 'film' | 'other') | null;
  artist?: (number | null) | Artist;
  reviewDate: string;
  listenedOn?: string | null;
  rating: number;
  format?: ('Vinyl' | 'CD' | 'Digital' | 'Stream' | 'Cassette' | 'Other') | null;
  label?: (number | null) | Label;
  releaseYear?: number | null;
  standoutTracks?: string | null;
  venue?: string | null;
  city?: string | null;
  eventDate?: string | null;
  tags?: string[] | null;
  /**
   * Album cover art. Suggested alt text: "Album Cover — Artist — Title"
   */
  cover?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  featured?: boolean | null;
  pinned?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs".
 */
export interface Song {
  id: number;
  title: string;
  artist: number | Artist;
  /**
   * Link to album review if one exists
   */
  album?: (number | null) | Review;
  /**
   * Album art / song artwork
   */
  cover?: (number | null) | Media;
  /**
   * Release date (optional)
   */
  released?: string | null;
  /**
   * Spotify track link (e.g. https://open.spotify.com/track/...)
   */
  spotifyUrl?: string | null;
  /**
   * Paste the Spotify embed iframe or URL — the src will be extracted automatically
   */
  spotifyEmbedUrl?: string | null;
  /**
   * YouTube link
   */
  youtubeUrl?: string | null;
  /**
   * Apple Music link
   */
  appleMusicUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gigs".
 */
export interface Gig {
  id: number;
  title: string;
  /**
   * Optional clickbait/SEO headline. Shows on cards and social shares. Falls back to title if empty.
   */
  headline?: string | null;
  slug: string;
  artist: number | Artist;
  venue: string;
  city: string;
  eventDate: string;
  tour?: string | null;
  support?: string | null;
  highlights?: string | null;
  tags?: string[] | null;
  cover?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  featured?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-dives".
 */
export interface DeepDive {
  id: number;
  title: string;
  /**
   * Optional clickbait/SEO headline. Shows on cards and social shares. Falls back to title if empty.
   */
  headline?: string | null;
  slug: string;
  publishedOn: string;
  topic?: string | null;
  era?: string | null;
  tags?: string[] | null;
  cover?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  featured?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists".
 */
export interface Playlist {
  id: number;
  title: string;
  /**
   * Optional clickbait/SEO headline. Shows on cards and social shares. Falls back to title if empty.
   */
  headline?: string | null;
  slug: string;
  publishedOn: string;
  platform: 'Spotify' | 'Apple Music' | 'YouTube' | 'Tidal' | 'Bandcamp' | 'Other';
  playlistUrl: string;
  /**
   * Paste the Spotify/Apple Music embed iframe or URL — the src will be extracted automatically
   */
  embedUrl?: string | null;
  mood?: string | null;
  duration?: number | null;
  tags?: string[] | null;
  cover?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  featured?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes".
 */
export interface Note {
  id: number;
  title: string;
  /**
   * Optional clickbait/SEO headline. Shows on cards and social shares. Falls back to title if empty.
   */
  headline?: string | null;
  slug: string;
  listenedOn: string;
  artist?: (number | null) | Artist;
  source?: string | null;
  tags?: string[] | null;
  cover?: (number | null) | Media;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  featured?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'artists';
        value: number | Artist;
      } | null)
    | ({
        relationTo: 'labels';
        value: number | Label;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'songs';
        value: number | Song;
      } | null)
    | ({
        relationTo: 'gigs';
        value: number | Gig;
      } | null)
    | ({
        relationTo: 'deep-dives';
        value: number | DeepDive;
      } | null)
    | ({
        relationTo: 'playlists';
        value: number | Playlist;
      } | null)
    | ({
        relationTo: 'notes';
        value: number | Note;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artists_select".
 */
export interface ArtistsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  image?: T;
  origin?: T;
  founded?: T;
  genre?: T;
  label?: T;
  spotifyUrl?: T;
  websiteUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels_select".
 */
export interface LabelsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  slug?: T;
  reviewType?: T;
  artist?: T;
  reviewDate?: T;
  listenedOn?: T;
  rating?: T;
  format?: T;
  label?: T;
  releaseYear?: T;
  standoutTracks?: T;
  venue?: T;
  city?: T;
  eventDate?: T;
  tags?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  published?: T;
  featured?: T;
  pinned?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs_select".
 */
export interface SongsSelect<T extends boolean = true> {
  title?: T;
  artist?: T;
  album?: T;
  cover?: T;
  released?: T;
  spotifyUrl?: T;
  spotifyEmbedUrl?: T;
  youtubeUrl?: T;
  appleMusicUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gigs_select".
 */
export interface GigsSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  slug?: T;
  artist?: T;
  venue?: T;
  city?: T;
  eventDate?: T;
  tour?: T;
  support?: T;
  highlights?: T;
  tags?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  published?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-dives_select".
 */
export interface DeepDivesSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  slug?: T;
  publishedOn?: T;
  topic?: T;
  era?: T;
  tags?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  published?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists_select".
 */
export interface PlaylistsSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  slug?: T;
  publishedOn?: T;
  platform?: T;
  playlistUrl?: T;
  embedUrl?: T;
  mood?: T;
  duration?: T;
  tags?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  published?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notes_select".
 */
export interface NotesSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  slug?: T;
  listenedOn?: T;
  artist?: T;
  source?: T;
  tags?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  published?: T;
  featured?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  songOfTheWeek?: {
    /**
     * Pick a song from the Songs collection
     */
    song?: (number | null) | Song;
    /**
     * e.g. "from People Watching" or "on repeat this week"
     */
    context?: string | null;
  };
  nowListening?: {
    /**
     * What you're listening to right now
     */
    song?: (number | null) | Song;
    /**
     * e.g. "On repeat" or "Late night vibes"
     */
    subtitle?: string | null;
    /**
     * Override link to Spotify/YouTube/etc
     */
    externalUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  songOfTheWeek?:
    | T
    | {
        song?: T;
        context?: T;
      };
  nowListening?:
    | T
    | {
        song?: T;
        subtitle?: T;
        externalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}